Removing a postgresql specific configuration from `ash_sqlite.install`
ash-project/ash_sqlite pull request #103
Opened 2024-11-17 00:20 UTC by djgoku

Not really sure how to test this except:

`mix igniter.new igniter_ash_phoenix_sqlite_remove_p_port_configuring --install ash,ash_phoenix,ash_sqlite@github:djgoku/ash_sqlite@chore-remove-setting-repo-port --with phx.new --with-args="--database sqlite3"` I have also attached the log below.

[removing-more-postgresql-log.txt](https://github.com/user-attachments/files/17788315/removing-more-postgresql-log.txt)

Just a thought, but if I am installing `ash_phoenix` and `ash_sqlite` could we just add an implicit `--with-args="--database sqlite3"` since if you don't you'll have a few bits of postgresql to remove since phx.new defaults to installing for postgresql. Not really sure how to solve this, but was just thinking about it.

2024-11-24 08:36 UTC, zachdaniel requested changes

2024-11-24 08:36 UTC, zachdaniel commented on lib/data_layer.ex
> -      Mix.Task.run("ash_postgres.rollback", args ++ ["-r", inspect(repo), "-n", to_string(n)])
We'd need to call the appropriate rollback tasks here not just remove them right?

2024-12-03 02:31 UTC, djgoku commented on lib/data_layer.ex
> -      Mix.Task.run("ash_postgres.rollback", args ++ ["-r", inspect(repo), "-n", to_string(n)])
Great catch! I switched this over to `ash_sqlite.rollback`

2024-12-03 13:25 UTC, zachdaniel approved these changes

2024-12-03 13:26 UTC, merged

2024-12-03 13:26 UTC, zachdaniel commented
🚀 Thank you for your contribution! 🚀